CREATE TABLE TB_BAIRRO (
    CD_BAIRRO BIGINT,
    TX_NOME VARCHAR(255),
    PRIMARY KEY (CD_BAIRRO)
);

CREATE TABLE TB_UF (
    CD_UF BIGINT,
    TX_NOME VARCHAR(255),
    PRIMARY KEY (CD_UF)
);

CREATE TABLE TB_PAIS (
    CD_PAIS BIGINT,
    TX_NOME VARCHAR(255),
    PRIMARY KEY (CD_PAIS)
);

CREATE TABLE TB_ENDERECO (
    CD_ENDERECO BIGINT PRIMARY KEY,
    TX_LOGRADOURO VARCHAR(255),
    NR_NUMERO INTEGER,
    TX_COMPLEMENTO VARCHAR(255),
    TX_CEP VARCHAR(255),
    CD_BAIRRO BIGINT,
    CD_UF BIGINT,
    CD_PAIS BIGINT,
    FOREIGN KEY (CD_BAIRRO) REFERENCES TB_BAIRRO(CD_BAIRRO),
    FOREIGN KEY (CD_UF) REFERENCES TB_UF(CD_UF),
    FOREIGN KEY (CD_PAIS) REFERENCES TB_PAIS(CD_PAIS)
);

CREATE TABLE TB_HABILIDADE (
    CD_HABILIDADE BIGINT PRIMARY KEY,
    TX_NOME VARCHAR(255)
);

CREATE TABLE TB_USUARIO (
    CD_USUARIO BIGINT PRIMARY KEY,
    TX_NOME VARCHAR(255),
    TX_EMAIL VARCHAR(255),
    DT_ANIVERSARIO TIMESTAMP,
    CD_ENDERECO BIGINT,
    FOREIGN KEY (CD_ENDERECO) REFERENCES TB_ENDERECO(CD_ENDERECO)
);

CREATE TABLE TB_USUARIO_HABILIDADE(
   CD_USUARIO BIGINT,
   CD_HABILIDADE BIGINT,
   PRIMARY KEY (CD_USUARIO, CD_HABILIDADE),
   FOREIGN KEY (CD_USUARIO) REFERENCES TB_USUARIO(CD_USUARIO),
   FOREIGN KEY (CD_HABILIDADE) REFERENCES TB_HABILIDADE(CD_HABILIDADE)
);